export type REPORT_TYPES = 'LAGGING_JOBS' | 'FLEX_JOBS' | 'SUBSCRIPTION_JOBS';

export const HC_LAGGING_TEMPLATE_ID = 'POC_LAGGING';
export const HC_FLEX_JOBS_TEMPLATE_ID = 'FLEX_JOBS_LAGGING';
export const HC_SUBSCRIPTION_JOBS_TEMPLATE_ID = 'SUBSCRIPTION_JOBS_LAGGING';